"""Report generation tools — PDF, AI-generated, and listing."""

from __future__ import annotations

from typing import Optional

from sheetstorm_bridge.client import SheetStormAPIError
from sheetstorm_bridge.server import get_client, mcp


def _format_report(r: dict) -> str:
    parts = [
        f"**{r.get('title', r.get('report_type', 'Report'))}** (ID: {r.get('id', 'N/A')})",
        f"  Type: {r.get('report_type', 'N/A')} | Format: {r.get('format', 'N/A')}",
        f"  Created: {r.get('created_at', 'N/A')}",
    ]
    if r.get("ai_provider"):
        parts.append(f"  AI Provider: {r['ai_provider']}")
    if r.get("generator"):
        gen = r["generator"]
        parts.append(f"  Generated by: {gen.get('name', gen.get('id', 'N/A'))}")
    return "\n".join(parts)


@mcp.tool()
async def sheetstorm_list_reports(incident_id: str) -> str:
    """List generated reports for an incident.

    Args:
        incident_id: UUID of the incident
    """
    client = get_client()
    try:
        data = await client.get(f"/incidents/{incident_id}/reports")
        items = data if isinstance(data, list) else data.get("items", data.get("reports", []))

        if not items:
            return "No reports found for this incident."

        lines = [f"**Reports** ({len(items)})\n"]
        for r in items:
            lines.append(_format_report(r))
            lines.append("")
        return "\n".join(lines)
    except SheetStormAPIError as exc:
        return f"✗ Error: {exc}"


@mcp.tool()
async def sheetstorm_generate_pdf_report(
    incident_id: str,
    report_type: str = "full",
    sections: Optional[str] = None,
) -> str:
    """Generate a PDF report for an incident.

    Args:
        incident_id: UUID of the incident
        report_type: Report type — one of: executive, full, metrics, ioc, trends
        sections: Optional comma-separated sections to include (defaults to the report type's sections)
    """
    client = get_client()
    try:
        payload: dict = {"report_type": report_type}
        if sections:
            payload["sections"] = [s.strip() for s in sections.split(",")]

        result = await client.post(f"/incidents/{incident_id}/reports/generate-pdf", json=payload)
        return f"✓ PDF report generated:\n{_format_report(result)}"
    except SheetStormAPIError as exc:
        return f"✗ Error: {exc}"


@mcp.tool()
async def sheetstorm_generate_ai_report(
    incident_id: str,
    summary_type: str = "executive",
    provider: Optional[str] = None,
) -> str:
    """Generate an AI-written summary of the incident from its timeline, hosts,
    accounts and IOCs using the backend AI service (returned as text, not stored).

    Args:
        incident_id: UUID of the incident
        summary_type: One of: executive, technical, recommendations
        provider: Optional AI provider name configured on the server (default: first available)
    """
    client = get_client()
    try:
        payload: dict = {"summary_type": summary_type}
        if provider:
            payload["provider"] = provider

        result = await client.post(f"/incidents/{incident_id}/reports/ai-generate", json=payload)
        summary = result.get("summary") if isinstance(result, dict) else None
        if not summary:
            return "✗ The AI service returned no summary."
        used = result.get("provider")
        header = f"✓ AI {result.get('summary_type', summary_type)} summary"
        if used:
            header += f" (provider: {used})"
        return f"{header}:\n\n{summary}"
    except SheetStormAPIError as exc:
        return f"✗ Error: {exc}"
