#!/usr/bin/env bash
# Build the release bundle for VERSION (used by .github/workflows/release.yml
# and the CI "Release bundle" job):
#
#   ci/release-assets.sh 1.0.1 [OUT]      (OUT defaults to dist/)
#
# OUT/docker-compose.yml          the stack on the published images, pinned to VERSION
# OUT/sheetstorm-VERSION.tar.gz   sheetstorm/{docker-compose.yml, .env.example,
#                                 install.sh, README.md, scripts/backup.sh,
#                                 scripts/restore.sh}
# OUT/sheetstorm.tar.gz           the same archive under a stable name, so
#                                 releases/latest/download/sheetstorm.tar.gz works
# OUT/SHA256SUMS
#
# docker-compose.yml is generated from the repository's docker-compose.yml +
# docker-compose.images.yml (`docker compose config --no-interpolate`), so it
# never drifts from the source stack. Its fixed project name ("sheetstorm")
# keeps the same volumes when a newer bundle is unpacked elsewhere.
set -euo pipefail

VERSION="${1:?usage: ci/release-assets.sh VERSION [OUT]}"
OUT="${2:-dist}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]] || { echo "release-assets: bad version $VERSION" >&2; exit 2; }
case "$OUT" in /*) ;; *) OUT="$PWD/$OUT" ;; esac

BUNDLE="$OUT/sheetstorm"
rm -rf "$BUNDLE" "$OUT/docker-compose.yml" "$OUT"/sheetstorm*.tar.gz "$OUT/SHA256SUMS"
mkdir -p "$BUNDLE/scripts"

{
  cat <<EOF
# SheetStorm ${VERSION}: the stack on the published images
# (ghcr.io/7a336e6e/sheetstorm-*, multi-arch, with build provenance).
# Generated by ci/release-assets.sh from docker-compose.yml and
# docker-compose.images.yml at this release; edit settings in .env, not here.
#
#   ./install.sh                       first install / upgrade (creates .env)
#   docker compose up -d               start with an existing .env
#
# SHEETSTORM_VERSION (default ${VERSION}) and SHEETSTORM_REGISTRY in .env
# override the image tag and registry.
EOF
  # Default project name, so volumes stay the same wherever the bundle is
  # unpacked; -p / COMPOSE_PROJECT_NAME still give a separate instance its
  # own volumes (no normalization: no hard-coded volume or network names).
  echo 'name: sheetstorm'
  # Every profile is kept: profiled services (ollama) stay opt-in at runtime.
  # No .env is read: nothing is interpolated.
  ( cd "$ROOT" && docker compose --env-file /dev/null -p sheetstorm -f docker-compose.yml -f docker-compose.images.yml \
      --profile '*' config --no-interpolate --no-path-resolution --no-normalize )
} | sed "s/\${SHEETSTORM_VERSION:?[^}]*}/\${SHEETSTORM_VERSION:-${VERSION}}/g" > "$BUNDLE/docker-compose.yml"

if grep -qE 'build:|SHEETSTORM_VERSION:\?|name: sheetstorm_' "$BUNDLE/docker-compose.yml"; then
  echo "release-assets: generated compose still builds, requires SHEETSTORM_VERSION or hard-codes volume names" >&2
  exit 1
fi

cp "$ROOT/.env.example" "$BUNDLE/.env.example"
cp "$ROOT/deploy/install.sh" "$BUNDLE/install.sh"
cp "$ROOT/deploy/README.md" "$BUNDLE/README.md"
cp "$ROOT/scripts/backup.sh" "$ROOT/scripts/restore.sh" "$BUNDLE/scripts/"
chmod 755 "$BUNDLE/install.sh" "$BUNDLE/scripts/"*.sh
cp "$BUNDLE/docker-compose.yml" "$OUT/docker-compose.yml"

# Stable archive metadata where GNU tar is available (CI); bsdtar otherwise.
TAR_FLAGS=()
if tar --version 2>/dev/null | grep -q GNU; then
  TAR_FLAGS=(--owner=0 --group=0 --numeric-owner --sort=name)
fi
COPYFILE_DISABLE=1 tar -C "$OUT" ${TAR_FLAGS[@]+"${TAR_FLAGS[@]}"} -czf "$OUT/sheetstorm-${VERSION}.tar.gz" sheetstorm
rm -rf "$BUNDLE"
cp "$OUT/sheetstorm-${VERSION}.tar.gz" "$OUT/sheetstorm.tar.gz"

FILES=(docker-compose.yml "sheetstorm-${VERSION}.tar.gz" sheetstorm.tar.gz)
( cd "$OUT" && { command -v sha256sum >/dev/null && sha256sum "${FILES[@]}" || shasum -a 256 "${FILES[@]}"; } > SHA256SUMS )
echo "release-assets: $(ls "$OUT" | tr '\n' ' ')" >&2
