"""MITRE ATT&CK Enterprise framework reference data.

Covers all 14 tactics with key techniques and sub-techniques relevant to
Windows/Linux/macOS incident response. Data aligned with ATT&CK v14.
"""

MITRE_ATTACK_TACTICS = [
    {"id": "TA0043", "name": "Reconnaissance", "description": "Gathering information to plan future adversary operations."},
    {"id": "TA0042", "name": "Resource Development", "description": "Establishing resources to support operations (infrastructure, accounts, capabilities)."},
    {"id": "TA0001", "name": "Initial Access", "description": "Trying to get into your network."},
    {"id": "TA0002", "name": "Execution", "description": "Trying to run malicious code."},
    {"id": "TA0003", "name": "Persistence", "description": "Trying to maintain their foothold."},
    {"id": "TA0004", "name": "Privilege Escalation", "description": "Trying to gain higher-level permissions."},
    {"id": "TA0005", "name": "Defense Evasion", "description": "Trying to avoid being detected."},
    {"id": "TA0006", "name": "Credential Access", "description": "Trying to steal account names and passwords."},
    {"id": "TA0007", "name": "Discovery", "description": "Trying to figure out your environment."},
    {"id": "TA0008", "name": "Lateral Movement", "description": "Trying to move through your environment."},
    {"id": "TA0009", "name": "Collection", "description": "Trying to gather data of interest to their goal."},
    {"id": "TA0011", "name": "Command and Control", "description": "Trying to communicate with compromised systems."},
    {"id": "TA0010", "name": "Exfiltration", "description": "Trying to steal data."},
    {"id": "TA0040", "name": "Impact", "description": "Trying to manipulate, interrupt, or destroy systems and data."},
]

MITRE_ATTACK_TECHNIQUES = [
    # === TA0043 — Reconnaissance ===
    {"id": "T1595", "name": "Active Scanning", "tactic": "Reconnaissance", "description": "Adversaries scan victim IP blocks to gather information (port scanning, vulnerability scanning).", "platforms": ["PRE"], "detection": "Network flow data, IDS signatures for scanning activity"},
    {"id": "T1595.001", "name": "Active Scanning: Scanning IP Blocks", "tactic": "Reconnaissance", "description": "Scanning IP ranges to identify live hosts, open ports, and services.", "platforms": ["PRE"], "detection": "Monitor for high-volume connection attempts from single source"},
    {"id": "T1595.002", "name": "Active Scanning: Vulnerability Scanning", "tactic": "Reconnaissance", "description": "Scanning for software vulnerabilities on externally-facing systems.", "platforms": ["PRE"], "detection": "WAF/IDS logs, connection patterns matching known scanner signatures"},
    {"id": "T1592", "name": "Gather Victim Host Information", "tactic": "Reconnaissance", "description": "Collecting information about victim hosts (hardware, software, configs) through scanning, phishing, or OSINT.", "platforms": ["PRE"], "detection": "Web server logs showing enumeration patterns"},
    {"id": "T1589", "name": "Gather Victim Identity Information", "tactic": "Reconnaissance", "description": "Collecting identity information (credentials, emails, names) via social engineering, breach data, or social media.", "platforms": ["PRE"], "detection": "Monitor for credential stuffing or enumeration attacks"},
    {"id": "T1590", "name": "Gather Victim Network Information", "tactic": "Reconnaissance", "description": "Gathering network configuration information such as IP ranges, domain names, and DNS records.", "platforms": ["PRE"], "detection": "DNS query logs, certificate transparency logs"},
    {"id": "T1591", "name": "Gather Victim Org Information", "tactic": "Reconnaissance", "description": "Collecting information about the target organization (structure, roles, business operations).", "platforms": ["PRE"], "detection": "Limited — primarily OSINT monitoring"},
    {"id": "T1598", "name": "Phishing for Information", "tactic": "Reconnaissance", "description": "Sending phishing messages to elicit sensitive information without delivering malware.", "platforms": ["PRE"], "detection": "Email gateway analysis, user awareness reporting"},

    # === TA0042 — Resource Development ===
    {"id": "T1583", "name": "Acquire Infrastructure", "tactic": "Resource Development", "description": "Purchasing/renting infrastructure (domains, servers, VPS) for operations.", "platforms": ["PRE"], "detection": "Domain registration monitoring, passive DNS"},
    {"id": "T1584", "name": "Compromise Infrastructure", "tactic": "Resource Development", "description": "Compromising third-party infrastructure for use in targeting.", "platforms": ["PRE"], "detection": "Threat intelligence feeds, anomalous traffic from known-good infrastructure"},
    {"id": "T1587", "name": "Develop Capabilities", "tactic": "Resource Development", "description": "Building malware, exploits, or tools to use during operations.", "platforms": ["PRE"], "detection": "Malware sandbox analysis, code similarity matching"},
    {"id": "T1585", "name": "Establish Accounts", "tactic": "Resource Development", "description": "Creating accounts on services (email, social media) for social engineering or infrastructure.", "platforms": ["PRE"], "detection": "Account creation monitoring, fake profile analysis"},
    {"id": "T1588", "name": "Obtain Capabilities", "tactic": "Resource Development", "description": "Acquiring tools, malware, exploits, or certificates for operations.", "platforms": ["PRE"], "detection": "Code signing certificate monitoring, exploit marketplace tracking"},

    # === TA0001 — Initial Access ===
    {"id": "T1566", "name": "Phishing", "tactic": "Initial Access", "description": "Sending phishing messages with malicious attachments or links to gain initial access.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Email gateway logs, URL analysis, attachment sandboxing (EID 4688 child of Outlook)"},
    {"id": "T1566.001", "name": "Phishing: Spearphishing Attachment", "tactic": "Initial Access", "description": "Targeted email with malicious attachment (DOC, PDF, LNK, ISO).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Email attachment analysis, Sysmon EID 11 file creation from email client processes"},
    {"id": "T1566.002", "name": "Phishing: Spearphishing Link", "tactic": "Initial Access", "description": "Targeted email containing a malicious URL.", "platforms": ["Windows", "macOS", "Linux"], "detection": "URL reputation, proxy logs, DNS Sysmon EID 22 from browser processes"},
    {"id": "T1190", "name": "Exploit Public-Facing Application", "tactic": "Initial Access", "description": "Exploiting vulnerabilities in internet-facing applications (web servers, VPN, email).", "platforms": ["Windows", "Linux"], "detection": "WAF logs, web server access logs, anomalous child processes from web services"},
    {"id": "T1133", "name": "External Remote Services", "tactic": "Initial Access", "description": "Leveraging external-facing remote services (VPN, RDP, Citrix) for initial access.", "platforms": ["Windows", "Linux"], "detection": "VPN/RDP authentication logs (EID 4624 Type 10), geo-impossible travel"},
    {"id": "T1078", "name": "Valid Accounts", "tactic": "Initial Access", "description": "Using legitimate credentials obtained through credential access for initial entry.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Anomalous logon patterns (EID 4624), impossible travel, MFA failures"},
    {"id": "T1189", "name": "Drive-by Compromise", "tactic": "Initial Access", "description": "Gaining access through a user visiting a compromised website (watering hole).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Proxy/URL filter logs, browser exploitation indicators, Sysmon EID 1 unusual browser children"},
    {"id": "T1195", "name": "Supply Chain Compromise", "tactic": "Initial Access", "description": "Manipulating products or delivery mechanisms before receipt by the consumer.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Software integrity verification, package hash monitoring"},
    {"id": "T1199", "name": "Trusted Relationship", "tactic": "Initial Access", "description": "Leveraging trust relationships with third parties (MSPs, partners) for access.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Monitor third-party VPN connections, service account activity"},

    # === TA0002 — Execution ===
    {"id": "T1059", "name": "Command and Scripting Interpreter", "tactic": "Execution", "description": "Abusing command and script interpreters to execute commands and scripts.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Process monitoring (EID 4688/Sysmon 1), PowerShell logging (EID 4104)"},
    {"id": "T1059.001", "name": "PowerShell", "tactic": "Execution", "description": "Using PowerShell commands and scripts for execution. Includes encoded commands, download cradles, and AMSI bypass.", "platforms": ["Windows"], "detection": "PowerShell Script Block Logging (EID 4104), Module Logging (EID 4103), encoded command detection"},
    {"id": "T1059.003", "name": "Windows Command Shell", "tactic": "Execution", "description": "Using cmd.exe to execute commands.", "platforms": ["Windows"], "detection": "Sysmon EID 1 with cmd.exe, parent process analysis"},
    {"id": "T1059.005", "name": "Visual Basic", "tactic": "Execution", "description": "Abusing VBScript or VBA macros for execution (Office macros, WScript).", "platforms": ["Windows"], "detection": "Office spawning child processes, Sysmon EID 1 wscript.exe/cscript.exe"},
    {"id": "T1059.007", "name": "JavaScript", "tactic": "Execution", "description": "Executing malicious JavaScript via wscript.exe, cscript.exe, or Node.js.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with JS interpreter processes, script content logging"},
    {"id": "T1204", "name": "User Execution", "tactic": "Execution", "description": "Relying upon user interaction (clicking links, opening files) to execute malicious code.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 from explorer.exe/Office, EID 11 file creation in Downloads"},
    {"id": "T1047", "name": "Windows Management Instrumentation", "tactic": "Execution", "description": "Using WMI to execute commands on local and remote systems.", "platforms": ["Windows"], "detection": "Sysmon EID 1 wmiprvse.exe children, WMI Activity (EID 5857-5861)"},
    {"id": "T1053", "name": "Scheduled Task/Job", "tactic": "Execution", "description": "Abusing task scheduling to execute code at defined times or on system boot.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4698 (task created), Sysmon EID 1 schtasks.exe, Task Scheduler EID 106"},
    {"id": "T1569", "name": "System Services", "tactic": "Execution", "description": "Abusing system service mechanisms (sc.exe, services) for execution.", "platforms": ["Windows"], "detection": "EID 4697/7045 (service install), Sysmon EID 1 sc.exe"},
    {"id": "T1106", "name": "Native API", "tactic": "Execution", "description": "Directly interacting with Windows API (NtCreateProcess, CreateProcess) for execution.", "platforms": ["Windows"], "detection": "API call monitoring, Sysmon driver-level events"},
    {"id": "T1203", "name": "Exploitation for Client Execution", "tactic": "Execution", "description": "Exploiting software vulnerabilities in client applications (browsers, Office, PDF readers) to execute code.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Crash reports, unusual child processes from client applications"},

    # === TA0003 — Persistence ===
    {"id": "T1547", "name": "Boot or Logon Autostart Execution", "tactic": "Persistence", "description": "Configuring system settings to automatically execute programs at boot or logon.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Registry monitoring (Sysmon EID 12/13), startup folder changes (EID 11)"},
    {"id": "T1547.001", "name": "Registry Run Keys / Startup Folder", "tactic": "Persistence", "description": "Adding entries to Run/RunOnce registry keys or Startup folder for persistence.", "platforms": ["Windows"], "detection": "Sysmon EID 13 targeting Run/RunOnce keys, EID 11 in Startup folder"},
    {"id": "T1543", "name": "Create or Modify System Process", "tactic": "Persistence", "description": "Creating or modifying system-level processes (services, daemons) for persistence.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4697/7045 new service, EID 7040 service config change"},
    {"id": "T1543.003", "name": "Windows Service", "tactic": "Persistence", "description": "Creating or modifying Windows services for persistence or privilege escalation.", "platforms": ["Windows"], "detection": "EID 4697 service install, sc.exe in Sysmon EID 1, registry ServiceDll changes"},
    {"id": "T1136", "name": "Create Account", "tactic": "Persistence", "description": "Creating accounts (local, domain, cloud) to maintain access.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4720 (user created), net user commands in Sysmon EID 1"},
    {"id": "T1098", "name": "Account Manipulation", "tactic": "Persistence", "description": "Manipulating existing accounts (adding credentials, permissions) for persistent access.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4738 (account changed), EID 4728/4732 (group membership)"},
    {"id": "T1053.005", "name": "Scheduled Task", "tactic": "Persistence", "description": "Creating scheduled tasks for persistent execution.", "platforms": ["Windows"], "detection": "EID 4698, schtasks.exe process creation, Task Scheduler EID 106"},
    {"id": "T1546", "name": "Event Triggered Execution", "tactic": "Persistence", "description": "Using system event-triggered mechanisms (WMI events, AppInit DLLs) for persistence.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 19-21 (WMI), registry AppInit_DLLs monitoring"},
    {"id": "T1574", "name": "Hijack Execution Flow", "tactic": "Persistence", "description": "Leveraging DLL search order hijacking, PATH manipulation, or dylib proxying for persistence.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 7 DLL loads from unusual paths, image load analysis"},
    {"id": "T1505", "name": "Server Software Component", "tactic": "Persistence", "description": "Abusing server software extensions (web shells, transport agents, SQL stored procedures).", "platforms": ["Windows", "Linux"], "detection": "File integrity monitoring, web shell signatures, unusual server child processes"},
    {"id": "T1505.003", "name": "Web Shell", "tactic": "Persistence", "description": "Deploying web-accessible backdoors on compromised web servers.", "platforms": ["Windows", "Linux"], "detection": "FIM on web directories, w3wp.exe/httpd child process monitoring, Sysmon EID 11"},

    # === TA0004 — Privilege Escalation ===
    {"id": "T1068", "name": "Exploitation for Privilege Escalation", "tactic": "Privilege Escalation", "description": "Exploiting software vulnerabilities to gain elevated privileges (kernel exploits, driver exploits).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Crash logs, unexpected SYSTEM-level processes, exploit signatures"},
    {"id": "T1134", "name": "Access Token Manipulation", "tactic": "Privilege Escalation", "description": "Manipulating access tokens to operate under different user or system security contexts.", "platforms": ["Windows"], "detection": "EID 4696 (token assigned), Sysmon EID 10 unusual process access"},
    {"id": "T1548", "name": "Abuse Elevation Control Mechanism", "tactic": "Privilege Escalation", "description": "Bypassing UAC, sudo, or other elevation control mechanisms.", "platforms": ["Windows", "macOS", "Linux"], "detection": "UAC bypass patterns, elevated processes from unexpected parents"},
    {"id": "T1548.002", "name": "Bypass User Account Control", "tactic": "Privilege Escalation", "description": "Bypassing Windows UAC to execute with elevated privileges.", "platforms": ["Windows"], "detection": "EID 4688 with elevated token, eventvwr.exe/fodhelper.exe abuse patterns"},
    {"id": "T1055", "name": "Process Injection", "tactic": "Privilege Escalation", "description": "Injecting code into another process to escalate privileges or evade defenses.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 8 (CreateRemoteThread), EID 10 (ProcessAccess to LSASS)"},

    # === TA0005 — Defense Evasion ===
    {"id": "T1070", "name": "Indicator Removal", "tactic": "Defense Evasion", "description": "Deleting or modifying artifacts (logs, files, timestamps) to remove evidence.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 1102 (log cleared), Sysmon EID 2 (timestomping), unexpected log gaps"},
    {"id": "T1070.001", "name": "Clear Windows Event Logs", "tactic": "Defense Evasion", "description": "Clearing Windows Event Logs to remove evidence of activity.", "platforms": ["Windows"], "detection": "EID 1102, wevtutil.exe in Sysmon EID 1"},
    {"id": "T1562", "name": "Impair Defenses", "tactic": "Defense Evasion", "description": "Disabling or tampering with security tools and defenses.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Defender EID 5001 (RTP disabled), Sysmon EID 16 (config changed), service stop events"},
    {"id": "T1562.001", "name": "Disable or Modify Tools", "tactic": "Defense Evasion", "description": "Disabling security tools (AV, EDR, SIEM agents) to avoid detection.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Service stop events (EID 7036), Defender EID 5001, Sysmon EID 16"},
    {"id": "T1036", "name": "Masquerading", "tactic": "Defense Evasion", "description": "Manipulating names/locations of artifacts to make them appear legitimate.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with mismatched image/described names, known path anomalies"},
    {"id": "T1027", "name": "Obfuscated Files or Information", "tactic": "Defense Evasion", "description": "Encoding, encrypting, or obfuscating payloads to evade detection.", "platforms": ["Windows", "macOS", "Linux"], "detection": "PowerShell EID 4104 with encoded content, entropy analysis of files"},
    {"id": "T1218", "name": "System Binary Proxy Execution", "tactic": "Defense Evasion", "description": "Using trusted system binaries (LOLBAS) to proxy execution of malicious content.", "platforms": ["Windows"], "detection": "Sysmon EID 1 monitoring LOLBins (mshta, rundll32, regsvr32, certutil)"},
    {"id": "T1218.011", "name": "Rundll32", "tactic": "Defense Evasion", "description": "Using rundll32.exe to execute malicious DLLs or JavaScript.", "platforms": ["Windows"], "detection": "Sysmon EID 1 with rundll32.exe, unusual DLL paths or JavaScript execution"},
    {"id": "T1112", "name": "Modify Registry", "tactic": "Defense Evasion", "description": "Modifying Windows Registry to hide configuration, disable security, or maintain persistence.", "platforms": ["Windows"], "detection": "Sysmon EID 12/13, registry integrity monitoring"},
    {"id": "T1140", "name": "Deobfuscate/Decode Files or Information", "tactic": "Defense Evasion", "description": "Using built-in utilities (certutil, base64) to decode obfuscated payloads.", "platforms": ["Windows", "macOS", "Linux"], "detection": "certutil -decode in Sysmon EID 1, file write events after decode operations"},
    {"id": "T1564", "name": "Hide Artifacts", "tactic": "Defense Evasion", "description": "Using hidden files, ADS, NTFS attributes, or VBA stomping to hide artifacts.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 15 (ADS), hidden attribute changes, file system integrity checks"},
    {"id": "T1055", "name": "Process Injection", "tactic": "Defense Evasion", "description": "Injecting code into running processes to evade process-based defenses.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 8 (CreateRemoteThread), EID 25 (process tampering), API monitoring"},

    # === TA0006 — Credential Access ===
    {"id": "T1003", "name": "OS Credential Dumping", "tactic": "Credential Access", "description": "Dumping credentials from OS storage (LSASS, SAM, NTDS.dit, /etc/shadow).", "platforms": ["Windows", "Linux"], "detection": "Sysmon EID 10 to lsass.exe, EID 9 (raw SAM access), volume shadow copy creation"},
    {"id": "T1003.001", "name": "LSASS Memory", "tactic": "Credential Access", "description": "Accessing LSASS process memory to extract passwords, hashes, and Kerberos tickets (Mimikatz).", "platforms": ["Windows"], "detection": "Sysmon EID 10 targeting lsass.exe, EID 1 procdump/comsvcs.dll usage"},
    {"id": "T1003.003", "name": "NTDS", "tactic": "Credential Access", "description": "Extracting credentials from Active Directory NTDS.dit database file.", "platforms": ["Windows"], "detection": "Volume shadow copy creation (vssadmin), ntdsutil.exe usage, Sysmon EID 1"},
    {"id": "T1110", "name": "Brute Force", "tactic": "Credential Access", "description": "Attempting many passwords/hashes to guess credentials (password spraying, stuffing).", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4625 (failed logons) spike, EID 4771 (Kerberos pre-auth failures)"},
    {"id": "T1558", "name": "Steal or Forge Kerberos Tickets", "tactic": "Credential Access", "description": "Stealing or forging Kerberos tickets (Kerberoasting, Golden Ticket, Silver Ticket).", "platforms": ["Windows"], "detection": "EID 4769 with RC4 encryption, abnormal TGT/TGS requests, EID 4768 anomalies"},
    {"id": "T1558.003", "name": "Kerberoasting", "tactic": "Credential Access", "description": "Requesting TGS tickets for SPN-enabled accounts to crack offline.", "platforms": ["Windows"], "detection": "EID 4769 with encryption type 0x17 (RC4), high-volume TGS requests from single account"},
    {"id": "T1552", "name": "Unsecured Credentials", "tactic": "Credential Access", "description": "Searching for credentials in files, registries, browser stores, or group policy preferences.", "platforms": ["Windows", "macOS", "Linux"], "detection": "File access monitoring for credential files, cmdkey.exe usage, browser credential API calls"},
    {"id": "T1187", "name": "Forced Authentication", "tactic": "Credential Access", "description": "Forcing authentication to capture hashes (LLMNR/NBT-NS poisoning, SMB relay).", "platforms": ["Windows"], "detection": "LLMNR/NBNS query logs, anomalous SMB authentication patterns"},
    {"id": "T1557", "name": "Adversary-in-the-Middle", "tactic": "Credential Access", "description": "Intercepting network communications to capture credentials or modify data in transit.", "platforms": ["Windows", "Linux"], "detection": "ARP anomalies, unexpected WPAD configurations, certificate errors"},

    # === TA0007 — Discovery ===
    {"id": "T1087", "name": "Account Discovery", "tactic": "Discovery", "description": "Attempting to enumerate local or domain accounts (net user, Get-ADUser).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with net.exe/dsquery.exe, EID 4798/4799 (group enumeration)"},
    {"id": "T1069", "name": "Permission Groups Discovery", "tactic": "Discovery", "description": "Enumerating group and permission settings (net group, Get-ADGroup).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with net.exe/gpresult.exe, LDAP query monitoring"},
    {"id": "T1082", "name": "System Information Discovery", "tactic": "Discovery", "description": "Gathering system information (hostname, OS version, architecture, patches).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with systeminfo.exe, ver, uname"},
    {"id": "T1083", "name": "File and Directory Discovery", "tactic": "Discovery", "description": "Enumerating files and directories on compromised systems.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with dir/tree/find commands, high-volume file access"},
    {"id": "T1016", "name": "System Network Configuration Discovery", "tactic": "Discovery", "description": "Gathering network configuration (ipconfig, ifconfig, route print).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with ipconfig/arp/nslookup/netsh commands"},
    {"id": "T1018", "name": "Remote System Discovery", "tactic": "Discovery", "description": "Attempting to discover other systems on the network (ping sweep, net view).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with net.exe/nltest.exe/ping.exe, network scan patterns"},
    {"id": "T1049", "name": "System Network Connections Discovery", "tactic": "Discovery", "description": "Enumerating network connections (netstat, ss, Get-NetTCPConnection).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with netstat.exe, Sysmon EID 3 from unusual processes"},
    {"id": "T1057", "name": "Process Discovery", "tactic": "Discovery", "description": "Enumerating running processes (tasklist, ps, Get-Process).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with tasklist.exe/Get-Process cmdlet"},
    {"id": "T1012", "name": "Query Registry", "tactic": "Discovery", "description": "Querying the Windows Registry for configuration and installed software information.", "platforms": ["Windows"], "detection": "Sysmon EID 1 with reg.exe query commands"},
    {"id": "T1518", "name": "Software Discovery", "tactic": "Discovery", "description": "Enumerating installed software, security tools, and versions.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with wmic product, Get-WmiObject, dpkg/rpm queries"},
    {"id": "T1201", "name": "Password Policy Discovery", "tactic": "Discovery", "description": "Discovering password policies to inform brute-force or credential attacks.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with net accounts, Get-ADDefaultDomainPasswordPolicy"},
    {"id": "T1482", "name": "Domain Trust Discovery", "tactic": "Discovery", "description": "Enumerating domain trust relationships (nltest, Get-ADTrust).", "platforms": ["Windows"], "detection": "Sysmon EID 1 with nltest.exe /domain_trusts, LDAP queries"},

    # === TA0008 — Lateral Movement ===
    {"id": "T1021", "name": "Remote Services", "tactic": "Lateral Movement", "description": "Using remote services (RDP, SSH, SMB, WinRM) to move between systems.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4624 Type 3/10, Sysmon EID 3 on RDP/SMB ports, WinRM EID 91"},
    {"id": "T1021.001", "name": "Remote Desktop Protocol", "tactic": "Lateral Movement", "description": "Using RDP to connect to remote systems.", "platforms": ["Windows"], "detection": "EID 4624 logon type 10, TerminalServices EID 21/1149, Sysmon EID 3 port 3389"},
    {"id": "T1021.002", "name": "SMB/Windows Admin Shares", "tactic": "Lateral Movement", "description": "Using SMB/Windows Admin Shares ($C, ADMIN$, IPC$) for lateral movement and file staging.", "platforms": ["Windows"], "detection": "EID 5140/5145 (share access), Sysmon EID 3 port 445, file creation on shares"},
    {"id": "T1021.006", "name": "Windows Remote Management", "tactic": "Lateral Movement", "description": "Using WinRM for command execution on remote systems.", "platforms": ["Windows"], "detection": "WinRM EID 6/91, Sysmon EID 1 wsmprovhost.exe, PowerShell remoting EID 53504"},
    {"id": "T1570", "name": "Lateral Tool Transfer", "tactic": "Lateral Movement", "description": "Transferring tools or files between systems within the compromised environment.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 11 file creation matching tool signatures, EID 3 internal file transfers"},
    {"id": "T1550", "name": "Use Alternate Authentication Material", "tactic": "Lateral Movement", "description": "Using alternative authentication material (pass-the-hash, pass-the-ticket) without plaintext passwords.", "platforms": ["Windows"], "detection": "EID 4624 with NTLM in pass-the-hash patterns, anomalous Kerberos tickets"},
    {"id": "T1550.002", "name": "Pass the Hash", "tactic": "Lateral Movement", "description": "Using NTLM hash to authenticate without the plaintext password.", "platforms": ["Windows"], "detection": "EID 4624 logon type 9 with NTLM, EID 4648 (explicit credential logon)"},

    # === TA0009 — Collection ===
    {"id": "T1560", "name": "Archive Collected Data", "tactic": "Collection", "description": "Compressing/encrypting collected data before exfiltration (zip, 7z, tar).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with archiving tools, large archive file creation events"},
    {"id": "T1005", "name": "Data from Local System", "tactic": "Collection", "description": "Searching for and collecting data from the local filesystem.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Unusual file access patterns, bulk read operations on sensitive directories"},
    {"id": "T1039", "name": "Data from Network Shared Drive", "tactic": "Collection", "description": "Collecting data from network shared drives accessible to the compromised account.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 5145 (detailed share access), high-volume file reads from shares"},
    {"id": "T1114", "name": "Email Collection", "tactic": "Collection", "description": "Collecting email data from local clients, servers, or remote services.", "platforms": ["Windows", "macOS"], "detection": "EWS/MAPI access logs, Outlook PST/OST file access, Exchange cmdlet monitoring"},
    {"id": "T1115", "name": "Clipboard Data", "tactic": "Collection", "description": "Collecting data stored in the clipboard (passwords, sensitive text).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 24 (clipboard capture), API call monitoring for GetClipboardData"},
    {"id": "T1056", "name": "Input Capture", "tactic": "Collection", "description": "Capturing user input (keylogging, credential capture from web portals).", "platforms": ["Windows", "macOS", "Linux"], "detection": "API hooking detection, Sysmon EID 7 suspicious DLL loads into user processes"},
    {"id": "T1074", "name": "Data Staged", "tactic": "Collection", "description": "Staging collected data in a central location before exfiltration.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Large file creation in temp/staging directories, unusual data aggregation patterns"},
    {"id": "T1113", "name": "Screen Capture", "tactic": "Collection", "description": "Taking screenshots to capture information displayed on user's screen.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Screenshot API monitoring, BMP/PNG creation in unusual directories"},

    # === TA0011 — Command and Control ===
    {"id": "T1071", "name": "Application Layer Protocol", "tactic": "Command and Control", "description": "Using application layer protocols (HTTP, HTTPS, DNS, SMTP) for C2 communication.", "platforms": ["Windows", "macOS", "Linux"], "detection": "DNS query patterns (Sysmon EID 22), proxy logs, network anomaly detection"},
    {"id": "T1071.001", "name": "Web Protocols", "tactic": "Command and Control", "description": "Using HTTP/HTTPS for C2 communication, often disguised as legitimate web traffic.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Proxy logs, unusual user-agents, beaconing interval analysis"},
    {"id": "T1071.004", "name": "DNS", "tactic": "Command and Control", "description": "Using DNS for C2 communication (DNS tunneling via TXT/CNAME records).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 22 with long/unusual DNS queries, high DNS query volume"},
    {"id": "T1105", "name": "Ingress Tool Transfer", "tactic": "Command and Control", "description": "Downloading additional tools or payloads from C2 or external infrastructure.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 11 files from browser/certutil/bitsadmin, proxy download logs"},
    {"id": "T1572", "name": "Protocol Tunneling", "tactic": "Command and Control", "description": "Tunneling C2 communications within other protocols (SSH tunneling, DNS-over-HTTPS).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Network flow analysis, unusual protocol behaviors on standard ports"},
    {"id": "T1090", "name": "Proxy", "tactic": "Command and Control", "description": "Using proxies (internal, external, multi-hop) to disguise C2 traffic origin.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Network flow analysis, unusual internal proxy configurations"},
    {"id": "T1573", "name": "Encrypted Channel", "tactic": "Command and Control", "description": "Using encrypted channels (symmetric/asymmetric) to conceal C2 communications.", "platforms": ["Windows", "macOS", "Linux"], "detection": "JA3/JA3S fingerprinting, certificate analysis, traffic entropy analysis"},
    {"id": "T1568", "name": "Dynamic Resolution", "tactic": "Command and Control", "description": "Dynamically resolving C2 infrastructure (DGA, DNS calc, CDN fronting).", "platforms": ["Windows", "macOS", "Linux"], "detection": "DGA detection algorithms, DNS NXDomain spikes, CDN anomaly monitoring"},
    {"id": "T1095", "name": "Non-Application Layer Protocol", "tactic": "Command and Control", "description": "Using non-application layer protocols (ICMP, raw TCP/UDP) for C2.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Unusual ICMP traffic, raw socket connection monitoring"},
    {"id": "T1102", "name": "Web Service", "tactic": "Command and Control", "description": "Using legitimate web services (GitHub, Pastebin, Google Drive, Dropbox) for C2.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Anomalous API calls to legitimate services, data volume analysis to external platforms"},

    # === TA0010 — Exfiltration ===
    {"id": "T1041", "name": "Exfiltration Over C2 Channel", "tactic": "Exfiltration", "description": "Exfiltrating data over the existing C2 communication channel.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Outbound data volume analysis, beaconing with varying payload sizes"},
    {"id": "T1048", "name": "Exfiltration Over Alternative Protocol", "tactic": "Exfiltration", "description": "Exfiltrating data via a different protocol than C2 (DNS, ICMP, FTP, SMTP).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Unusual outbound protocols, DNS query data exfiltration, FTP/SMTP from non-standard processes"},
    {"id": "T1567", "name": "Exfiltration Over Web Service", "tactic": "Exfiltration", "description": "Using legitimate web services (cloud storage, webhooks) for data exfiltration.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Unusual uploads to cloud services, API calls to file-sharing platforms from servers"},
    {"id": "T1029", "name": "Scheduled Transfer", "tactic": "Exfiltration", "description": "Scheduling data exfiltration at set intervals to blend with normal traffic.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Periodic outbound data spikes, scheduled task/cron analysis"},
    {"id": "T1537", "name": "Transfer Data to Cloud Account", "tactic": "Exfiltration", "description": "Transferring data to adversary-controlled cloud accounts.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Cloud storage API monitoring, unusual S3/Blob/GCS operations"},

    # === TA0040 — Impact ===
    {"id": "T1486", "name": "Data Encrypted for Impact", "tactic": "Impact", "description": "Encrypting data on target systems to disrupt availability (ransomware).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Mass file rename/modification (Sysmon EID 11), encryption API calls, ransom note creation"},
    {"id": "T1490", "name": "Inhibit System Recovery", "tactic": "Impact", "description": "Deleting volume shadow copies, backups, or disabling recovery features.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Sysmon EID 1 with vssadmin/wbadmin/bcdedit, EID 524 (catalog deleted)"},
    {"id": "T1489", "name": "Service Stop", "tactic": "Impact", "description": "Stopping critical services to disrupt functionality (databases, security tools).", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 7036 (service stopped), sc.exe stop commands, Get-Service/Stop-Service in PowerShell logs"},
    {"id": "T1485", "name": "Data Destruction", "tactic": "Impact", "description": "Destroying data and files on specific systems or in large numbers across a network.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Mass file deletion events, Sysmon EID 23/26, wiper signature detection"},
    {"id": "T1491", "name": "Defacement", "tactic": "Impact", "description": "Modifying visual content (internal/external) to deliver messaging or intimidation.", "platforms": ["Windows", "macOS", "Linux"], "detection": "Web content integrity monitoring, file modification on web server directories"},
    {"id": "T1499", "name": "Endpoint Denial of Service", "tactic": "Impact", "description": "Performing endpoint-level DoS to degrade or block availability (resource exhaustion).", "platforms": ["Windows", "macOS", "Linux"], "detection": "Resource utilization spikes, process creation storms, network flood patterns"},
    {"id": "T1529", "name": "System Shutdown/Reboot", "tactic": "Impact", "description": "Shutting down or rebooting systems to disrupt availability.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 1074 (shutdown initiated), Sysmon EID 1 shutdown.exe/init commands"},
    {"id": "T1531", "name": "Account Access Removal", "tactic": "Impact", "description": "Interrupting availability by modifying/deleting accounts or changing passwords.", "platforms": ["Windows", "macOS", "Linux"], "detection": "EID 4726 (user deleted), EID 4724 (mass password resets), EID 4725 (account disabled)"},
]

MITRE_ATTACK_TACTIC_IDS = {t["id"]: t for t in MITRE_ATTACK_TACTICS}
MITRE_ATTACK_TECHNIQUE_IDS = {t["id"]: t for t in MITRE_ATTACK_TECHNIQUES}
MITRE_ATTACK_TACTIC_NAMES = {t["name"]: t for t in MITRE_ATTACK_TACTICS}
