"""MITRE D3FEND countermeasure reference data.

Expanded catalogue of defensive techniques mapped to ATT&CK techniques,
organized by D3FEND tactic (Harden, Detect, Isolate, Deceive, Evict, Restore).
"""

D3FEND_TECHNIQUES = [
    # === Harden ===
    {"id": "D3-ACL", "name": "Access Control List", "tactic": "Harden", "description": "Restrict resource access using discretionary or mandatory access control lists.", "mitre_attack_mappings": ["T1078", "T1098", "T1136"], "examples": ["Windows NTFS ACLs", "Linux file permissions", "Network ACLs on routers"]},
    {"id": "D3-MFA", "name": "Multi-Factor Authentication", "tactic": "Harden", "description": "Require multiple authentication factors to verify identity before granting access.", "mitre_attack_mappings": ["T1078", "T1110", "T1556"], "examples": ["TOTP apps", "FIDO2 hardware keys", "SMS verification (less secure)"]},
    {"id": "D3-AAEM", "name": "Application Allow/Deny List", "tactic": "Harden", "description": "Restrict application execution to explicitly approved or blocked executables.", "mitre_attack_mappings": ["T1059", "T1204", "T1218"], "examples": ["AppLocker", "Windows Defender Application Control (WDAC)", "SELinux policies"]},
    {"id": "D3-HBPI", "name": "Host-Based Privilege Isolation", "tactic": "Harden", "description": "Implement least-privilege separation on endpoints to limit process capabilities.", "mitre_attack_mappings": ["T1068", "T1134", "T1548"], "examples": ["Windows UAC", "Linux capabilities", "grsecurity RBAC"]},
    {"id": "D3-EHPV", "name": "Email Header Parameter Validation", "tactic": "Harden", "description": "Validate email header authenticity using SPF, DKIM, and DMARC.", "mitre_attack_mappings": ["T1566", "T1598"], "examples": ["SPF records", "DKIM signing", "DMARC reject policy"]},
    {"id": "D3-DA", "name": "Domain Allowlisting", "tactic": "Harden", "description": "Restricting network access to only approved domains via DNS filtering.", "mitre_attack_mappings": ["T1071", "T1102", "T1568"], "examples": ["DNS sinkhole", "Pi-hole", "Cisco Umbrella allowlists"]},
    {"id": "D3-PAN", "name": "Physical Access Restriction", "tactic": "Harden", "description": "Control physical access to systems, media, and network infrastructure.", "mitre_attack_mappings": ["T1200", "T1091"], "examples": ["Badge access controls", "USB port locks", "Server room biometrics"]},
    {"id": "D3-SBV", "name": "Service Binary Verification", "tactic": "Harden", "description": "Verify integrity of service binaries via signing and hash validation.", "mitre_attack_mappings": ["T1543", "T1574"], "examples": ["Authenticode signing", "RPM/DEB package signing", "CI/CD artifact signing"]},
    {"id": "D3-DLIC", "name": "Driver Load Integrity Checking", "tactic": "Harden", "description": "Verify digital signatures on kernel-mode drivers before loading.", "mitre_attack_mappings": ["T1014", "T1068"], "examples": ["Windows HVCI", "Secure Boot", "Linux kernel module signing"]},
    {"id": "D3-CP", "name": "Credential Hardening", "tactic": "Harden", "description": "Strengthen credential storage and policies to resist theft and brute-force attacks.", "mitre_attack_mappings": ["T1003", "T1110", "T1552"], "examples": ["Credential Guard", "LAPS", "Password vaulting (CyberArk, HashiCorp)"]},
    {"id": "D3-FE", "name": "File Encryption", "tactic": "Harden", "description": "Encrypt files at rest to protect sensitive data from unauthorized access.", "mitre_attack_mappings": ["T1005", "T1039", "T1074"], "examples": ["BitLocker", "LUKS", "VeraCrypt volumes"]},
    {"id": "D3-NE", "name": "Network Encryption", "tactic": "Harden", "description": "Encrypt network communications to prevent interception and tampering.", "mitre_attack_mappings": ["T1557", "T1040"], "examples": ["IPsec tunnels", "WireGuard VPN", "TLS 1.3 enforcement"]},

    # === Detect ===
    {"id": "D3-NTA", "name": "Network Traffic Analysis", "tactic": "Detect", "description": "Analyze network traffic patterns and content to identify malicious activity.", "mitre_attack_mappings": ["T1071", "T1095", "T1572"], "examples": ["Zeek/Bro IDS", "Suricata", "Network flow analysis (NetFlow/sFlow)"]},
    {"id": "D3-PSA", "name": "Process Spawn Analysis", "tactic": "Detect", "description": "Monitor process creation events for anomalous parent-child relationships and command lines.", "mitre_attack_mappings": ["T1059", "T1053", "T1569"], "examples": ["Sysmon EID 1 monitoring", "CrowdStrike process tree", "YARA process scanning"]},
    {"id": "D3-SFA", "name": "System File Analysis", "tactic": "Detect", "description": "Monitor and analyze system file creation, modification, and deletion events.", "mitre_attack_mappings": ["T1547", "T1574", "T1505"], "examples": ["Sysmon EID 11/23", "OSSEC file integrity monitoring", "Tripwire"]},
    {"id": "D3-FAPA", "name": "File Access Pattern Analysis", "tactic": "Detect", "description": "Detect anomalous file access patterns indicating data collection or ransomware.", "mitre_attack_mappings": ["T1005", "T1486", "T1083"], "examples": ["Ransomware canary files", "User behavior analytics (UBA)", "Varonis DatAlert"]},
    {"id": "D3-DNSA", "name": "DNS Traffic Analysis", "tactic": "Detect", "description": "Analyze DNS queries for indicators of C2 communication, tunneling, or DGA activity.", "mitre_attack_mappings": ["T1071.004", "T1568", "T1048"], "examples": ["Sysmon EID 22", "Passive DNS monitoring", "DGA classifier ML models"]},
    {"id": "D3-SICA", "name": "System Init Config Analysis", "tactic": "Detect", "description": "Monitor startup configuration changes (registry Run keys, services, scheduled tasks).", "mitre_attack_mappings": ["T1547.001", "T1543.003", "T1053.005"], "examples": ["Autoruns analysis", "Sysmon EID 12/13 registry monitoring", "systemd unit file monitoring"]},
    {"id": "D3-RRDD", "name": "Remote Registry Discovery Detection", "tactic": "Detect", "description": "Detect remote access to the Windows Registry for reconnaissance or configuration changes.", "mitre_attack_mappings": ["T1012", "T1112", "T1021.002"], "examples": ["EID 4657 remote registry access", "Named pipe monitoring", "Sysmon EID 17/18"]},
    {"id": "D3-UBA", "name": "User Behavior Analysis", "tactic": "Detect", "description": "Baseline and monitor user activity patterns to detect account compromise or insider threats.", "mitre_attack_mappings": ["T1078", "T1021", "T1550"], "examples": ["Microsoft Sentinel UEBA", "Exabeam", "Splunk UBA"]},
    {"id": "D3-PCSV", "name": "Process Code Segment Verification", "tactic": "Detect", "description": "Verify integrity of code segments in running processes to detect injection.", "mitre_attack_mappings": ["T1055", "T1134"], "examples": ["Microsoft ETW providers", "unhooking detection", "Sysmon EID 25 (process tampering)"]},
    {"id": "D3-ISVA", "name": "Inbound Session Volume Analysis", "tactic": "Detect", "description": "Monitor inbound session volumes for brute-force, scanning, or DoS indicators.", "mitre_attack_mappings": ["T1110", "T1595", "T1499"], "examples": ["Failed logon thresholds", "Connection rate limiting", "Firewall session tracking"]},
    {"id": "D3-CSPP", "name": "Client-Server Payload Profiling", "tactic": "Detect", "description": "Profile and analyze payload characteristics in client-server communications.", "mitre_attack_mappings": ["T1071.001", "T1105", "T1573"], "examples": ["JA3/JA3S TLS fingerprinting", "HTTP user-agent profiling", "Payload entropy analysis"]},
    {"id": "D3-ANET", "name": "Authentication Event Thresholding", "tactic": "Detect", "description": "Set thresholds on authentication events to detect credential attacks.", "mitre_attack_mappings": ["T1110", "T1187", "T1558"], "examples": ["Account lockout policies", "EID 4625 alert rules", "Adaptive MFA triggers"]},
    {"id": "D3-PMAD", "name": "Process Memory Access Detection", "tactic": "Detect", "description": "Detect access to process memory, particularly for credential dumping tools.", "mitre_attack_mappings": ["T1003.001", "T1055"], "examples": ["Sysmon EID 10 targeting lsass.exe", "Windows Credential Guard alerts", "EDR memory access rules"]},

    # === Isolate ===
    {"id": "D3-NI", "name": "Network Isolation", "tactic": "Isolate", "description": "Segment the network to limit lateral movement between zones and VLANs.", "mitre_attack_mappings": ["T1021", "T1570", "T1080"], "examples": ["VLAN segmentation", "Microsegmentation (VMware NSX, Illumio)", "Air-gapped networks"]},
    {"id": "D3-EI", "name": "Execution Isolation", "tactic": "Isolate", "description": "Isolate process execution using sandboxes, containers, or virtual machines.", "mitre_attack_mappings": ["T1204", "T1566.001", "T1203"], "examples": ["Browser sandbox (Chrome Site Isolation)", "Docker/Podman containers", "Application sandboxing (Firejail)"]},
    {"id": "D3-HCI", "name": "Hardware-Based Containment Isolation", "tactic": "Isolate", "description": "Use hardware-based mechanisms (TPM, TEE, SGX enclaves) for security-critical isolation.", "mitre_attack_mappings": ["T1003", "T1068"], "examples": ["Intel SGX enclaves", "ARM TrustZone", "TPM-sealed credentials"]},
    {"id": "D3-OTF", "name": "Outbound Traffic Filtering", "tactic": "Isolate", "description": "Filter and restrict outbound network traffic to limit C2 and exfiltration channels.", "mitre_attack_mappings": ["T1041", "T1048", "T1567"], "examples": ["Egress firewall rules", "Proxy with SSL inspection", "DNS sinkhole blocking"]},
    {"id": "D3-ITF", "name": "Inbound Traffic Filtering", "tactic": "Isolate", "description": "Filter and restrict inbound network traffic to reduce attack surface.", "mitre_attack_mappings": ["T1190", "T1133", "T1595"], "examples": ["WAF rules", "IPS inline blocking", "GeoIP filtering"]},
    {"id": "D3-ANAA", "name": "Administrative Network Activity Analysis", "tactic": "Isolate", "description": "Restrict and monitor administrative network protocols to dedicated management VLANs.", "mitre_attack_mappings": ["T1021.001", "T1021.002", "T1021.006"], "examples": ["PAW (Privileged Access Workstations)", "Jump servers/bastion hosts", "Admin VLAN isolation"]},

    # === Deceive ===
    {"id": "D3-DE", "name": "Decoy Environment", "tactic": "Deceive", "description": "Deploy realistic decoy environments (honeynets) to attract and study adversary behavior.", "mitre_attack_mappings": ["T1595", "T1190", "T1021"], "examples": ["Thinkst Canary", "T-Pot honeypot platform", "Active Directory deception (AD Bait)"]},
    {"id": "D3-DF", "name": "Decoy File", "tactic": "Deceive", "description": "Plant decoy files with monitoring to detect unauthorized access or exfiltration attempts.", "mitre_attack_mappings": ["T1005", "T1039", "T1083"], "examples": ["Honeydoc files with beacons", "Canary tokens in documents", "Fake credential files in admin shares"]},
    {"id": "D3-DNR", "name": "Decoy Network Resource", "tactic": "Deceive", "description": "Deploy fake network resources (shares, services, databases) to detect lateral movement.", "mitre_attack_mappings": ["T1018", "T1021", "T1570"], "examples": ["Honeypot SMB shares", "Fake SQL servers", "Decoy RDP servers with alerting"]},
    {"id": "D3-DUC", "name": "Decoy User Credential", "tactic": "Deceive", "description": "Create fake credential entries that trigger alerts when used.", "mitre_attack_mappings": ["T1003", "T1110", "T1558"], "examples": ["Honeypot AD accounts", "Fake cached credentials", "Decoy API keys in config files"]},
    {"id": "D3-DST", "name": "Decoy Session Token", "tactic": "Deceive", "description": "Plant fake session tokens or cookies that trigger alerts when replayed.", "mitre_attack_mappings": ["T1550", "T1539"], "examples": ["Canary cookies", "Fake Kerberos tickets", "Honeypot OAuth tokens"]},

    # === Evict ===
    {"id": "D3-CE", "name": "Credential Eviction", "tactic": "Evict", "description": "Revoke and rotate compromised credentials (passwords, tokens, certificates, keys).", "mitre_attack_mappings": ["T1003", "T1078", "T1550"], "examples": ["Mass password reset", "Kerberos krbtgt double-rotation", "Certificate revocation (CRL/OCSP)"]},
    {"id": "D3-PE", "name": "Process Eviction", "tactic": "Evict", "description": "Terminate and clean up malicious processes and their persistence mechanisms.", "mitre_attack_mappings": ["T1059", "T1055", "T1547"], "examples": ["taskkill /F malicious PID", "Clean Run key entries", "Remove scheduled tasks and services"]},
    {"id": "D3-AEv", "name": "Account Eviction", "tactic": "Evict", "description": "Disable, lock, or delete adversary-created or compromised accounts.", "mitre_attack_mappings": ["T1136", "T1098", "T1078"], "examples": ["Disable compromised AD accounts", "Revoke OAuth sessions", "Remove unauthorized local accounts"]},
    {"id": "D3-FEv", "name": "File Eviction", "tactic": "Evict", "description": "Remove malicious files, web shells, implants, and staged data from systems.", "mitre_attack_mappings": ["T1505.003", "T1059", "T1204"], "examples": ["Delete web shells from IIS/Apache", "Remove dropped malware binaries", "Purge staging directories"]},

    # === Restore ===
    {"id": "D3-BAS", "name": "Baseline Configuration Restore", "tactic": "Restore", "description": "Restore systems to known-good baseline configurations after compromise.", "mitre_attack_mappings": ["T1547", "T1543", "T1112"], "examples": ["Group Policy refresh", "Golden image re-deployment", "Configuration management (Ansible/Puppet) enforcement"]},
    {"id": "D3-DRe", "name": "Data Restore", "tactic": "Restore", "description": "Restore data from backups after destructive attacks (ransomware, wipers).", "mitre_attack_mappings": ["T1486", "T1485", "T1490"], "examples": ["Restore from offline backups", "Volume shadow copy restoration", "Cloud snapshot recovery"]},
    {"id": "D3-SRe", "name": "Service Restore", "tactic": "Restore", "description": "Restore disrupted services and applications to operational state.", "mitre_attack_mappings": ["T1489", "T1529", "T1499"], "examples": ["Service restart with clean configs", "Failover to DR site", "Container re-deployment from clean images"]},
    {"id": "D3-IRe", "name": "Identity Restore", "tactic": "Restore", "description": "Restore identity infrastructure after compromise (AD, PKI, federation).", "mitre_attack_mappings": ["T1003.003", "T1558", "T1531"], "examples": ["AD forest recovery", "PKI certificate re-issuance", "Federation trust re-establishment"]},
]

D3FEND_TACTICS = sorted(set(t["tactic"] for t in D3FEND_TECHNIQUES))
D3FEND_TECHNIQUE_IDS = {t["id"]: t for t in D3FEND_TECHNIQUES}
